### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by k-p-ani** [GoogleCloudPlatform/anthos-bare-metal-ref-arch#4]
In the documentation for "Deploy to self-managed hosts" at 
https://github.com/GoogleCloudPlatform/anthos-bare-metal-ref-arch/blob/main/docs/deploy-to-hosts.md

in point number 9, there is reference to vars.sh under folder "scripts",
is this file missing from repo or the documentation has to be updated ?

**Comment by arueth** [comment]
The `vars.sh` file gets created when you run the `./scripts/helpers/set_variables.sh` script.
